language: node_js
sudo: required
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq p7zip-full
install:
  - npm install xpath
  - npm install xmldom
  - npm install node-7z
  - npm install json2csv
