language: node_js
sudo: required
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq p7zip-full
install:
  - npm install xpath
  - npm install xmldom
  - npm install --save node-7z
  - npm install json2csv --save
